#!/bin/bash

echo "Compiling *comp* *comp*"

# OTP Key
gcc -o keygen keygen.c

# Encryption
gcc -o otp_enc otp_enc.c
gcc -o otp_enc_d otp_enc_d.c

# Decryption
gcc -o otp_dec otp_dec.c
gcc -o otp_dec_d otp_dec_d.c

